### ISSUE TITLE
Mercadopago support

### ISSUE THREAD

**Issue by EduardoZepeda** [jazzband/django-payments#236]
I'm seeing that there is an active PR for Mercado Pago, but lacks refund and cancel functionality 

I have a working mercadopago (MX) payment gateway backend compatible with django-payments, with some tests, pip installation and fully operational [here](https://github.com/EduardoZepeda/django-payments-mercadopago). If you like I can send a PR so it can be added to your Additional payment providers section. 

In case you're not interested just close this issue. Thank you.

**Comment by WhyNotHugo** [comment]
Hi. Sorry for the very late reply, I somehow missed this before.

The PR is actually in a very functional state and I've been using that branch on production since even before I published it here.

I mostly haven't merged it in due to it missing tests (I really want to polish it finely before merging). I'll try to finalise the missing bits on that PR and merge it, and we can then discuss what improvements can be merged in from your separate package.

I'll leave this open for future discussion for now, but would most definitely welcome improvements. I also think it's very valuable to avoid duplicating the maintenance effort we're doing :)

**Comment by WhyNotHugo** [comment]
MP support is shipping with v0.15.0.
